Add site option
gammaboard/gammaboard pull request #11
Opened 2019-03-29 14:58 UTC by mikael10j

2019-03-29 19:10 UTC, vuillaut requested changes

2019-03-29 19:10 UTC, vuillaut commented on gammaboard.py
>      Create the figure holding the resolution plots for the dashboard
Would be good to edit the args in the docstring for the functions that have new parameters

2019-03-29 19:10 UTC, vuillaut commented on gammaboard.py
> +    ctaplot.plot_angular_res_cta_performance(site, ax=ax_ang_res, color='black', label=site)
Why was the label not displayed in the figures in gammaboard?
Is it now?

2019-04-01 14:47 UTC, mikael10j commented on gammaboard.py
>      Create the figure holding the resolution plots for the dashboard
solved in c5a65dd

2019-04-01 14:49 UTC, mikael10j commented on gammaboard.py
> +    ctaplot.plot_angular_res_cta_performance(site, ax=ax_ang_res, color='black', label=site)
The labels were indeed not displayed. This is now done thanks to the call to axes.legend().
The site argument has been removed in c5a65dd to not override the default one.

2019-04-01 15:07 UTC, vuillaut approved these changes

2019-04-01 15:09 UTC, merged