Update effective area and resolution curves
gammaboard/gammaboard pull request #19
Opened 2019-05-24 14:36 UTC by mikael10j

Effective area:
- Compute effective area with simulation information
- Compute effective area for:
  - triggered events (maximum effective area)
  - reconstructed events (after selection cuts)
  - after discrimination (in case of full analysis)

Resolution curves: 
- Compute resolution curves for:
  - reconstructed events (after selection cuts)
  - after discrimination (in case of full analysis)

2019-05-26 22:12 UTC, vuillaut requested changes
Super, merci pour ces changements.
Deux petits points à discuter.

2019-05-26 22:12 UTC, vuillaut commented on gammaboard.py
> +    max_scatter_range = -np.inf
Je ne comprends pas ces initialisations et les vérifications qui s'en suivent.

2019-05-26 22:12 UTC, vuillaut commented on gammaboard.py
> +        print(min_alt)
to be removed

2019-05-27 09:51 UTC, mikael10j commented on gammaboard.py
> +    max_scatter_range = -np.inf
résolu par 0a9624a

2019-05-27 09:52 UTC, mikael10j commented on gammaboard.py
> +        print(min_alt)
résolu par 0a9624a

2019-05-27 11:03 UTC, vuillaut commented on gammaboard.py
No need to store all values, I would have proposed something along the following.
But I guess there are not many values anyway to store so we won't run into an issue here.


```
    spectral_index = None
    max_scatter_range = None
    
    
    for row in run_config:
        spectral_index = row['spectral_index'][0] if spectral_index is None else spectral_index
        max_scatter_range = row['max_scatter_range'][0] if max_scatter_range is None else max_scatter_range
    assert spectral_index == row['spectral_index'][0]
    assert max_scatter_range == row['max_scatter_range'][0]
```

2019-05-27 11:05 UTC, vuillaut commented on gammaboard.py
Or even 
```
spectral_index = run_config[0]['spectral_index'][0]
...
for row in run_config[1:]:
    assert spectral_index = row['spectral_index'][0]
    ...
```

2019-05-28 09:56 UTC, vuillaut commented
@mikael10j you tested on lappuds ?

2019-05-28 10:15 UTC, mikael10j commented
Nope, only on my computer.

2019-06-18 17:57 UTC, vuillaut commented on gammaboard.py
> +        trig_events = pd.read_hdf(experiments_directory + '/' + experiment + '/' + experiment + '.h5',
These events could actually be a sub-selection of triggered events.
Right now, for example, the events not passing the reconstruction process are not save in the result file.
But I agree on the principle, in a perfect world (a.k.a. the future), all triggered events would end-up in the DL2 file with a tag saying reconstructed or not.

2019-06-18 18:09 UTC, mikael10j commented on gammaboard.py
> +        trig_events = pd.read_hdf(experiments_directory + '/' + experiment + '/' + experiment + '.h5',
I don't understand your point. For now `trig_events` contains the list of all triggered event's energy, to compute the maximum reachable effective area.

2019-06-18 18:10 UTC, vuillaut approved these changes

2019-06-18 18:13 UTC, vuillaut commented on gammaboard.py
> +        trig_events = pd.read_hdf(experiments_directory + '/' + experiment + '/' + experiment + '.h5',
With the files created from GammaLearn yes, but this is not necessarily the case.
My example was referring to lstchain. 
In any case, this is not a big deal, just a naming convention.

2019-06-19 07:27 UTC, merged