Install
gammaboard/gammaboard pull request #22
Opened 2019-08-23 18:04 UTC by vuillaut

GammaBoard becomes an installable package, yeah!

- add setup.py and so on for install
- move `gammaboard.py` and `dashboard.ipynb` in gammaboard folder for clarity
- add gif in shared data
- update to ctaplot v0.3.0
- fix API change for ctaplot v0.3.0

the dashboard can be lunch from anywhere with a simple `gammaboard` command, see the README instructions.

2019-08-26 12:02 UTC, mikael10j requested changes
`pip install gammaboard` doesn't work yet.

`python setup.py install` fails
> error: can't copy 'g': doesn't exist or not a regular file

Beside, there is a merge conflict.

2019-08-27 10:37 UTC, mikael10j requested changes
I still have an install error:

> running install
running bdist_egg
running egg_info
creating gammaboard.egg-info
writing gammaboard.egg-info/PKG-INFO
writing dependency_links to gammaboard.egg-info/dependency_links.txt
writing entry points to gammaboard.egg-info/entry_points.txt
writing requirements to gammaboard.egg-info/requires.txt
writing top-level names to gammaboard.egg-info/top_level.txt
writing manifest file 'gammaboard.egg-info/SOURCES.txt'
reading manifest file 'gammaboard.egg-info/SOURCES.txt'
writing manifest file 'gammaboard.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/gammaboard
copying gammaboard/gammaboard.py -> build/lib/gammaboard
copying gammaboard/__init__.py -> build/lib/gammaboard
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/gammaboard
copying build/lib/gammaboard/gammaboard.py -> build/bdist.linux-x86_64/egg/gammaboard
copying build/lib/gammaboard/__init__.py -> build/bdist.linux-x86_64/egg/gammaboard
byte-compiling build/bdist.linux-x86_64/egg/gammaboard/gammaboard.py to gammaboard.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/gammaboard/__init__.py to __init__.cpython-36.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
error: can't copy 'g': doesn't exist or not a regular file

what is your Python version ?

2019-08-27 10:40 UTC, vuillaut commented
> I still have an install error:
> 
> > running install
> > running bdist_egg
> > running egg_info
> > creating gammaboard.egg-info
> > writing gammaboard.egg-info/PKG-INFO
> > writing dependency_links to gammaboard.egg-info/dependency_links.txt
> > writing entry points to gammaboard.egg-info/entry_points.txt
> > writing requirements to gammaboard.egg-info/requires.txt
> > writing top-level names to gammaboard.egg-info/top_level.txt
> > writing manifest file 'gammaboard.egg-info/SOURCES.txt'
> > reading manifest file 'gammaboard.egg-info/SOURCES.txt'
> > writing manifest file 'gammaboard.egg-info/SOURCES.txt'
> > installing library code to build/bdist.linux-x86_64/egg
> > running install_lib
> > running build_py
> > creating build
> > creating build/lib
> > creating build/lib/gammaboard
> > copying gammaboard/gammaboard.py -> build/lib/gammaboard
> > copying gammaboard/**init**.py -> build/lib/gammaboard
> > creating build/bdist.linux-x86_64
> > creating build/bdist.linux-x86_64/egg
> > creating build/bdist.linux-x86_64/egg/gammaboard
> > copying build/lib/gammaboard/gammaboard.py -> build/bdist.linux-x86_64/egg/gammaboard
> > copying build/lib/gammaboard/**init**.py -> build/bdist.linux-x86_64/egg/gammaboard
> > byte-compiling build/bdist.linux-x86_64/egg/gammaboard/gammaboard.py to gammaboard.cpython-36.pyc
> > byte-compiling build/bdist.linux-x86_64/egg/gammaboard/**init**.py to **init**.cpython-36.pyc
> > installing package data to build/bdist.linux-x86_64/egg
> > running install_data
> > error: can't copy 'g': doesn't exist or not a regular file
> 
> what is your Python version ?

Travis is installing without any issue using python 3.6

2019-08-27 11:15 UTC, mikael10j approved these changes

2019-08-27 11:18 UTC, merged